name: School13
options:
  bundleIdPrefix: com.2phmcjkm9bglitch
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
targets:
  School13:
    type: application
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Sources/App/Info.plist
      properties:
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIStatusBarHidden: true
        CFBundleDisplayName: "Школа №13"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.2phmcjkm9bglitch.school13
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: NO
